### ISSUE TITLE
[BUG] Android back button not affecting the SplitView

### ISSUE THREAD

**Issue by mfrischbutter** [toshiaki-h/split_view#24]
# Issue
Currently if you are pressing the android back button, the action does not pop the context of the SplitView, it would try to pop the context of the Navigator.

# Expected Result
If you are currently inside one View after using SplitView.push(), you are pressing the back button, i would expect SplitView.pop() would be called, instead of Navigator.pop().

# Hotfix
I already tried to fix it somehow with a WillPopScope, but somehow i am not able to but it inside the child or placeholder of the SplitView Widget. It does not get called. Only if the SplitView is the child, it would be get called, but i dont have the context of the SplitView in this case and can't pop the SplitView.

# Solution
Add a controller to be able to control the SplitView outside of context, or try to fix the WillPopScope, so it would automatically choose the right action.

**Comment by toshiaki-h** [comment]
@mfrischbutter 
Thank you for reporting the issue.
Can you show me the code where I can see the problem?

**Comment by mfrischbutter** [comment]
I'll prepare an example code

**Comment by mfrischbutter** [comment]
Oh, i'm sorry. I'm using the flutter_split_view package not split_view...
The functionalities are a little bit different... Thank you anyways for the fast reply
